spring:
  datasource:
    url: jdbc:mysql://umc-db.chv5tzvovpuq.ap-northeast-2.rds.amazonaws.com:3306/temp
    username: admin
    password: q!w2e3r4t5
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create